import React from "react";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "MyPSU - authentication",
  description: "Generated by create next app",
};

export default async function AuthLayout(
  {
    children
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <div className="flex h-screen">
      <div className="flex w-full h-full items-center justify-center">
        {children}
      </div>
    </div>
  );
}
