import { type ThemeConfig } from 'tailwindcss/types/config';

export const lineHeight: ThemeConfig['lineHeight'] = {
  h1Large: 'var(--large-h1-line-height)',
  h2Large: 'var(--large-h2-line-height)',
  h3Large: 'var(--large-h3-line-height)',
  h1Title: 'var(--title-h1-line-height)',
  h2Title: 'var(--title-h2-line-height)',
  h3Title: 'var(--title-h3-line-height)',
  h1Subtitle: 'var(--subtitle-h1-line-height)',
  h2Subtitle: 'var(--subtitle-h2-line-height)',
  buttonLarge: 'var(--button-large-line-height)',
  buttonSmall: 'var(--button-small-line-height)',
  bodyLarge: 'var(--body-large-line-height)',
  bodyLargeBold: 'var(--body-large-line-height)',
  bodyMedium: 'var(--body-medium-line-height)',
  bodyMediumBold: 'var(--body-medium-bold-line-height)',
  bodySmall: 'var(--body-small-line-height)',
  bodySmallSemibold: 'var(--body-small-semibold-line-height)',
  bodySmallBold: 'var(--body-small-bold-line-height)',
  overlineLarge: 'var(--overline-large-line-height)',
  overlineSmall: 'var(--overline-small-line-height)',
  tag: 'var(--tag-line-height)',
  mobil: 'var(--mobil-line-height)',
};
