import React from "react";
import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import "./globals.css";
import { Header, Sidebar } from "@/components";
import {AuthProvider} from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(
  {
    children,
    params
  }: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
  }>) {
  // Получаем текущий язык и проверяем, что он корректный
  const { locale } = await params;
  if (!routing.locales.includes(locale as 'en' | 'ru')) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} className="min-h-screen">
    <body className="antialiased flex h-screen">
    <NextIntlClientProvider messages={messages}>
      <AuthProvider>
        <Sidebar />
        <div className="flex-1 flex flex-col">
          <Header />
          {children}
        </div>
      </AuthProvider>
    </NextIntlClientProvider>
    </body>
    </html>
  );
}
