import React from "react";
import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import "./globals.css";
import {AuthProvider} from "@/context/AuthContext";
import {BreadcrumbProvider} from "@/context/BreadcrumbContext";

export const metadata: Metadata = {
  title: "MyPSU",
  description: "Generated by create next app",
};

export default async function RootLayout(
  {
    children,
    params
  }: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
  }>) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as 'en' | 'ru')) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} className="min-h-screen">
    <body className="antialiased min-h-screen">
    <NextIntlClientProvider messages={messages}>
      <AuthProvider>
        <BreadcrumbProvider>
          {children}
        </BreadcrumbProvider>
      </AuthProvider>
    </NextIntlClientProvider>
    </body>
    </html>
  );
}
