import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "MyPSU - authentication",
  description: "Generated by create next app",
};

export default async function AuthLayout(
  {
    children
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <div className="flex w-full h-screen items-center justify-center">
        {children}
    </div>
  );
}
