import React from "react";
import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import '../styles/ui.scss';
import { getUserLocale } from '@/services/locale';
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
    title: "MyPSU",
    description: "Generated by create next app",
};

export default async function LocaleLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    const locale = await getUserLocale();
    const messages = await getMessages();

    return (
        <html lang={locale}>
        <body
            className='antialiased'
        >
        <NextIntlClientProvider messages={messages}>
            <div className='min-h-screen h-screen'>
                {children}
            </div>
            <Toaster />
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
